# Generated by Django 3.0.7 on 2020-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='homePost',
        ),
    ]
