# Generated by Django 3.0.7 on 2020-06-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
